trigger:
  branches:
    include:
    - main
    - test
    - features/*
  tags:
    include:
    - "*"    
  paths:
    include:
    - terraform/*

pool:
  name: ahpazuremanageddevops

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:    
    - template: variables/prd.yml
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/test') }}:    
    - template: variables/tst.yml
  - ${{ else }}:
    - template: variables/dev.yml

stages:
- stage: tf_bootstrap_storage
  variables:
    - group: ${{variables.keyVaultName}}
    - template: /variables/${{variables.env}}.yml
  jobs:
    - job: bootstrap_storage
      displayName: Bootstrap Terraform State Storage
      steps:
        - task: TerraformInstaller@1
          inputs:
            version: 'latest'

        - script: |
            echo "Initializing Terraform for bootstrap storage..."
            az account set -s $(dataPlatformSubscriptionName)
            cd $(System.DefaultWorkingDirectory)/terraform/tf-bootstrap-storage

            # Set Azure provider authentication variables
            export ARM_SUBSCRIPTION_ID=$(dataPlatformSubscriptionId)
            export ARM_CLIENT_ID=$(apdap-devops-sc-client-id)
            export ARM_CLIENT_SECRET=$(apdap-devops-sc-client-secret)
            export ARM_TENANT_ID="0d739c66-dcf8-4b06-87ab-9052bd918a5f"

            echo "tfvars/${{variables.env}}.tfvars"
            echo "{{variables.env}}"
            echo "asdadas: $(env)"

            terraform init
            terraform plan -var-file="tfvars/${{variables.env}}.tfvars" -out="$(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan"
            terraform apply -var-file="tfvars/${{variables.env}}.tfvars" -auto-approve "$(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan"
          displayName: Terraform Apply for Bootstrap Storage

        - script: |
            echo "Fetching backend configuration dynamically..."
            cd $(System.DefaultWorkingDirectory)/terraform/tf-bootstrap-storage
            RESOURCE_GROUP=$(terraform output -raw resource_group_name)
            STORAGE_ACCOUNT=$(terraform output -raw storage_account_name)
            CONTAINER_NAME=$(terraform output -raw container_name)

            echo "##vso[task.setvariable variable=bootstrap_resource_group;isOutput=true]$RESOURCE_GROUP"
            echo "##vso[task.setvariable variable=bootstrap_storage_account;isOutput=true]$STORAGE_ACCOUNT"
            echo "##vso[task.setvariable variable=bootstrap_container_name;isOutput=true]$CONTAINER_NAME"
          name: stagevars
          displayName: Set Backend Configuration Variables

- stage: tf_state_management
  variables:
    - group: ${{variables.keyVaultName}}
  dependsOn: tf_bootstrap_storage
  jobs:
    - job: terraform_state_management
      variables:
        bootstrap_resource_group: $[stageDependencies.tf_bootstrap_storage.bootstrap_storage.outputs['stagevars.bootstrap_resource_group']]
        bootstrap_storage_account: $[stageDependencies.tf_bootstrap_storage.bootstrap_storage.outputs['stagevars.bootstrap_storage_account']]
        bootstrap_container_name: $[stageDependencies.tf_bootstrap_storage.bootstrap_storage.outputs['stagevars.bootstrap_container_name']]
      displayName: Terraform State Management
      steps:
        - task: TerraformInstaller@1
          inputs:
            version: 'latest'
        - script: |
            echo "Using dynamic backend configuration..."
            cd $(System.DefaultWorkingDirectory)/terraform

            # Set Azure provider authentication variables
            export ARM_SUBSCRIPTION_ID=$(dataPlatformSubscriptionId)
            export ARM_CLIENT_ID=$(apdap-devops-sc-client-id)
            export ARM_CLIENT_SECRET=$(apdap-devops-sc-client-secret)
            export ARM_TENANT_ID="0d739c66-dcf8-4b06-87ab-9052bd918a5f"

            az account set -s $(dataPlatformSubscriptionName)
            terraform init -backend-config="resource_group_name=$(bootstrap_resource_group)" \
                           -backend-config="storage_account_name=$(bootstrap_storage_account)" \
                           -backend-config="container_name=$(bootstrap_container_name)" \
                           -backend-config="key=terraform.tfstate"
          displayName: Terraform Init with Dynamic Backend

- stage: Terraform_run
  variables:
    - group: ${{variables.keyVaultName}}
    - template: /variables/${{variables.env}}.yml
  dependsOn: 
    - tf_bootstrap_storage
    - tf_state_management
  jobs:
  - job: terraform_plan
    variables:
        bootstrap_resource_group: $[stageDependencies.tf_bootstrap_storage.bootstrap_storage.outputs['stagevars.bootstrap_resource_group']]
        bootstrap_storage_account: $[stageDependencies.tf_bootstrap_storage.bootstrap_storage.outputs['stagevars.bootstrap_storage_account']]
        bootstrap_container_name: $[stageDependencies.tf_bootstrap_storage.bootstrap_storage.outputs['stagevars.bootstrap_container_name']]
    displayName: Terraform State Management
    steps:
      - task: TerraformInstaller@1
        inputs:
          version: 'latest'
      - template: terraform/templates/terraform-plan.yml
        parameters:
          env: $(env)
          serviceConnection: $(serviceConnection)
          dataPlatformPrincipalId: $(apdap-devops-sc-client-id)
          dataPlatformPrincipalKey: $(apdap-devops-sc-client-secret)
          dataPlatformSubscriptionId: $(dataPlatformSubscriptionId)
          dataPlatformSubscriptionName: $(dataPlatformSubscriptionName)
          bootstrap_resource_group: $(bootstrap_resource_group)
          bootstrap_storage_account: $(bootstrap_storage_account)
          bootstrap_container_name: $(bootstrap_container_name)
          
      - template: terraform/templates/terraform-apply.yml
        parameters:
          env: $(env)
          serviceConnection: $(serviceConnection)
          dataPlatformPrincipalId: $(apdap-devops-sc-client-id)
          dataPlatformPrincipalKey: $(apdap-devops-sc-client-secret)
          dataPlatformSubscriptionId: $(dataPlatformSubscriptionId)
          dataPlatformSubscriptionName: $(dataPlatformSubscriptionName)
          bootstrap_resource_group: $(bootstrap_resource_group)
          bootstrap_storage_account: $(bootstrap_storage_account)
          bootstrap_container_name: $(bootstrap_container_name)
