# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: ahpazuremanageddevops

trigger:
- main

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - name: ENVIRONMENT
      value: TST
  - ${{ else }}:
    - name: ENVIRONMENT
      value: DEV

  - group: AbaKeyVault-${{ variables.ENVIRONMENT }}

steps:

- script: |
    echo ${{ variables.ENVIRONMENT }}
  displayName: 'echo the variable'
