trigger:
  branches:
    include:
    - main
    - test
    - features/*
  tags:
    include:
    - "*"    
  paths:
    include:
    - terraform/*

pool:
  name: ahpazuremanageddevops

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:    
    - template: variables/prd.yml
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/test') }}:    
    - template: variables/tst.yml
  - ${{ else }}:
    - template: variables/dev.yml

stages:
- stage: Terraform_run
  variables:
    - group: ${{variables.keyVaultName}}
  jobs:
  - job: terraform_plan
    steps:
      - task: TerraformInstaller@1
        inputs:
          version: 'latest'
      - template: templates/terraform-plan.yml
        parameters:
          env: $(env)
          serviceConnection: $(serviceConnection)
          dataPlatformPrincipalId: $(apdap-devops-sc-client-id)
          dataPlatformPrincipalKey: $(apdap-devops-sc-client-secret)
          dataPlatformSubscriptionId: $(dataPlatformSubscriptionId)
          dataPlatformSubscriptionName: $(dataPlatformSubscriptionName)
      - template: templates/terraform-apply.yml
        parameters:
          env: $(env)
          serviceConnection: $(serviceConnection)
          dataPlatformPrincipalId: $(apdap-devops-sc-client-id)
          dataPlatformPrincipalKey: $(apdap-devops-sc-client-secret)
          dataPlatformSubscriptionId: ${{ dataPlatformSubscriptionId }}
          dataPlatformSubscriptionName: ${{ dataPlatformSubscriptionName }}
