trigger:
  branches:
    include:
    - main
    - test
    - features/*
  tags:
    include:
    - "*"    
  paths:
    include:
    - platform/*

pool:
  name: ahpazuremanageddevops

variables:
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
    - template: variables/prd.yml
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:    
    - template: variables/acc.yml
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/test') }}:    
    - template: variables/tst.yml
  - ${{ else }}:
    - template: variables/dev.yml


stages:
- stage: adssa
  variables:
      - group: ${{variables.keyVaultName}}
  jobs:
  - job: terraform_plan
    steps:
    - script: |
        # Install Azure CLI
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        
        # Install Terraform
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install terraform
      displayName: 'Install Azure CLI and Terraform'

    - script: |
        echo apdap-devops-sc-tst-client-id : $(apdap-devops-sc-tst-client-id)
        echo apdap-devops-sc-tst-client-secret : $(apdap-devops-sc-tst-client-secret)
      displayName: 'Set Terraform values'


    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo " ==== set Terraform values for using azure resources ====="
          export ARM_CLIENT_ID="ac373095-2e54-4920-ad36-2f92dbf05e6a"
          export ARM_CLIENT_SECRET= "er~8Q~khvFA0CwzOUUcAkLdA5s84IAdLzvH.PcqY"
          export ARM_TENANT_ID= "0d739c66-dcf8-4b06-87ab-9052bd918a5f"
          export ARM_SUBSCRIPTION_ID= "22aa9b03-5bec-414b-8814-fa975beb8e08"

          # Terraform steps
          az account list
          az account set --subscription="22aa9b03-5bec-414b-8814-fa975beb8e08"
          cd $(System.DefaultWorkingDirectory)/terraform
          terraform init \
            -backend-config="backendconfigs/tst.hcl"
          terraform plan -var-file="terraform.tfvars"
          terraform apply -auto-approve -var-file="terraform.tfvars"
        addSpnToEnvironment: true
      displayName: 'Terraform apply'
