variables:
  - name: dataPlatformSubscriptionId
    value: 22aa9b03-5bec-414b-8814-fa975beb8e08
  - name: dataPlatformSubscriptionName
    value: Azure_subscription_1
  - name: env
    value: DEV
  - name: keyVaultName
    value: AbaKeyVault-DEV
  - name: serviceConnection
    value: apdap-devops-sc-dev
  - name: servicePrincipleId
    value: apdap-devops-sc-dev-client-id
  - name: serviceConnectionSecret
    value: apdap-devops-sc-dev-client-secret